### ISSUE TITLE
网易云热评接口

### ISSUE THREAD

**Issue by schizobulia** [fangzesheng/free-api#13]
- [接口地址](https://www.yuque.com/anruofusheng/kb/zknilp)
- [示例](https://api.dongkji.com/api/v1/api//poetry/2833324528@qq.com)
- 返回参数说明
```
{
    c: '评论',
    a: '歌曲名称',
    d: '来源',
    l: '歌曲链接',
}
```

**Comment by fangzesheng** [comment]
非常感谢！
